// Generated by CoffeeScript 1.6.3
var drawBranch, elem, line, numOfBud, numOfLoop, params, two;

elem = document.getElementById('content').children[0];

params = {
  width: 1000,
  height: 1000
};

two = new Two(params).appendTo(elem);

numOfLoop = 4;

numOfBud = 1;

line = 0;

drawBranch = function(x1, y1, x2, y2, i) {
  var j, _i, _results;
  line = two.makeLine(x1, y1, x2, y2);
  console.log("...");
  line.linewidth = 19 - 5 * i;
  if (i > numOfLoop) {

  } else {
    _results = [];
    for (j = _i = 1; 1 <= numOfBud ? _i <= numOfBud : _i >= numOfBud; j = 1 <= numOfBud ? ++_i : --_i) {
      _results.push(arguments.callee(x2, y2, x2 + 200 * Math.random(), y2 + 200 * Math.random(), i + 1));
    }
    return _results;
  }
};

drawBranch(10, 10, 200, 200, 0);

two.update();
